spring:
    application:
        name: api-gateway
# Default Spring Profile
server:
    error:
        include-message: always

logging:
    level:
        root: INFO
        com.example: DEBUG

---

# for docker

spring:
    config:
        activate:
            on-profile: docker

app:
    customers-service:
        host: customers-service
        port: 8080
    deliveries-service:
        host: deliveries-service
        port: 8080
    furniture-service:
        host: furniture-service
        port: 8080
    purchases-service:
        host: purchases-service
        port: 8080

