Server:
    error:
        include-message: always
    port: 8080


logging:
    level:
        root: INFO
        com.panaritis: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    # for docker
spring:
    datasource:
        url: jdbc:mysql://mysql_server3/furniture-db
        username: user
        password: secretpwd

    jpa:
        hibernate:
            ddl-auto: none

    config:
        activate:
            on-profile: docker

    sql:
        init:
            platform: mysql
            mode: always

---
# for test  using h2
spring:
    config:
        activate:
            on-profile: h2
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:FurnitureStoreApp-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
            #let jpa create the schema
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                auto-quote-keyword: true
        defer-datasource-initialization: true
    sql:
        init:
            platform: h2
            mode: always

